### ISSUE TITLE
Data flow between nodes?

### ISSUE THREAD

**Issue by alelordelo** [AudioKit/Flow#29]
### Description

Thanks for sharing such  beautiful designed package!

Sorry if it’s a dumb question, but…

How can I add a function to a node? A dead simple hello world would be super useful for the demo!

Cheers from Stockholm

### Proposed Solution

.

### Describe Alternatives You've Considered

.

**Comment by wtholliday** [comment]
Hi @alelordelo , Flow only handles the user interface for a data-flow graph. It's up to you to implement processing.

best

**Comment by alelordelo** [comment]
Ah got it!

Will do some googling to see if I find a tutorial on how set a proper data flow for flow graphs ...

thanks!
