### ISSUE TITLE
Example / clarity on how to add nodes

### ISSUE THREAD

**Issue by dirkx** [AudioKit/Flow#35]
### Description

My compliments for flow; very neat & easy to keep the data model in sync with the UI & lovely editing for the wires.

But am wondering if an example is needed that shows how to _add_ a node (or delete) at runtime.

I had expected something like below to be possible - but am clearly missing something obvious.

```
import SwiftUI
import Combine
import Flow

@main
struct FlowDemoApp: App {
    var fcv = FlowContentView.init()
    var body: some Scene {
        WindowGroup {
            // FlowContentView()
            fcv;
        }
        .commands {
            CommandMenu("Nodes") {
                Button(action: {
                    // fcv.addNode();
                    let newNode = Node(name: "PID", titleBarColor: Color.red,
                                  inputs: ["in1", "in2"], outputs: ["out"]);
                    fcv.patch.nodes.append(newNode)
                }, label: {
                    Text("Add Node")
                });
            }
        }
    }
}
```

### Proposed Solution

Adding something to the example that adds a node would be most lovely

### Describe Alternatives You've Considered

Tried various other options (obviously recreating and redrawing works)

**Comment by wtholliday** [comment]
@dirkx I added a button in demo. I suspect there's a problem with your code because it seems to store a view as a var.

**Comment by dirkx** [comment]
Perfect & clear ! Thanks.
